import Head from "next/head"
import { Footer, Navbar } from "../../common"

const PageLayout = ({ children }: any) => {
  return (
    <>
      <div className='mx-auto max-w-7xl px-4 space-y-8 sm:px-6 lg:px-8'>
        <Head>
          <title>Portfolio - Michael Adenugba</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='relative z-10 bg-white pb-8 sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32'>
          {/* Navbar Starts */}
          <Navbar />
          {/* Navbar Ends */}
        </div>

        <div className='mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8'>
          {children}
        </div>
      </div>
      <Footer />
    </>
  )
}

export default PageLayout
